// app/layout.tsx (Server Component, no "use client")
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ClientLayout from "../components/ClientLayout";

export const metadata: Metadata = {
  title: "Moon style Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative z-10 bg-black text-white">
        <Toaster />
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
