import type { Metadata } from "next";

import "./globals.css";
import Providers from "../components/Providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Moon style Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const showBackground =
    typeof window !== "undefined" ? window.location.pathname === "/" : true;
    // console.log(showBackground)
  return (
    <html lang="en">
      <body className="relative z-10">
        <Toaster/>
        {showBackground ? <Providers>{children}</Providers> : <>{children}</>}
      </body>
    </html>
  );
}
